// dom-framework-benchmark/angular/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

type Priority = 'Low' | 'Medium' | 'High';
type Task = { id: number; name: string; priority: Priority };

const priorities: Priority[] = ['Low', 'Medium', 'High'];

function makeTasks(count: number): Task[] {
  return Array.from({ length: count }, (_, index) => ({
    id: index + 1,
    name: `Task ${index + 1}`,
    priority: priorities[index % priorities.length]
  }));
}
function mutateFirst50(tasks: Task[]): Task[] {
  return tasks.map((task, index) => index < 50 ? ({
    ...task,
    name: `${task.name} updated`,
    priority: priorities[(priorities.indexOf(task.priority) + 1) % priorities.length]
  }) : task);
}
function heapMB(): number | null {
  const perf = performance as Performance & { memory?: { usedJSHeapSize: number } };
  return perf.memory ? Math.round((perf.memory.usedJSHeapSize / 1024 / 1024) * 100) / 100 : null;
}
function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}
function afterPaint(): Promise<void> {
  return new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './app.component.html'
})
export class AppComponent {
  tasks = signal<Task[]>([]);
  metrics = signal<Record<string, { ms: number; heapMB: number | null }> | null>(null);
  running = signal(false);
  name = '';
  priority: Priority = 'Medium';

  makeTasksForTemplate(count: number) { return makeTasks(count); }
  metricEntries(values: Record<string, { ms: number; heapMB: number | null }>) { return Object.entries(values); }

  addTask() {
    if (!this.name.trim()) return;
    this.tasks.update(old => [...old, { id: Date.now(), name: this.name.trim(), priority: this.priority }]);
    this.name = '';
  }
  updateTask(id: number) {
    this.tasks.update(old => old.map(t => t.id === id ? { ...t, name: `${t.name} edited` } : t));
  }
  removeTask(id: number) {
    this.tasks.update(old => old.filter(t => t.id !== id));
  }
  async sample(operation: () => void) {
    const start = performance.now();
    operation();
    await afterPaint();
    return performance.now() - start;
  }
  async runBenchmark() {
    this.running.set(true);
    const results: Record<string, { ms: number; heapMB: number | null }> = {};

    for (const count of [100, 500, 1000]) {
      const samples: number[] = [];
      for (let i = 0; i < 5; i++) {
        this.tasks.set([]); await afterPaint();
        samples.push(await this.sample(() => this.tasks.set(makeTasks(count))));
      }
      results[`render_${count}`] = { ms: median(samples), heapMB: heapMB() };
    }

    const updates: number[] = [];
    for (let i = 0; i < 5; i++) {
      this.tasks.set(makeTasks(1000)); await afterPaint();
      updates.push(await this.sample(() => this.tasks.update(mutateFirst50)));
    }
    results['update_50'] = { ms: median(updates), heapMB: heapMB() };

    const deletions: number[] = [];
    for (let i = 0; i < 5; i++) {
      this.tasks.set(makeTasks(1000)); await afterPaint();
      deletions.push(await this.sample(() => this.tasks.update(old => old.slice(50))));
    }
    results['delete_50'] = { ms: median(deletions), heapMB: heapMB() };

    this.metrics.set(results);
    this.running.set(false);
  }
  downloadResults() {
    const blob = new Blob([JSON.stringify({ framework: 'Angular', generatedAt: new Date().toISOString(), results: this.metrics() }, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'angular-results.json'; a.click(); URL.revokeObjectURL(url);
  }
}

<main class="app">
  <header>
    <div><div class="eyebrow">Angular DOM Benchmark</div><h1>TodoBench</h1><div class="muted">Signals + @for + track task.id</div></div>
    <button (click)="runBenchmark()" [disabled]="running()">{{ running() ? 'Benchmarking…' : 'Run benchmark' }}</button>
  </header>

  <form class="form-row" (submit)="$event.preventDefault(); addTask()">
    <input [(ngModel)]="name" name="name" placeholder="Task name">
    <select [(ngModel)]="priority" name="priority"><option>Low</option><option>Medium</option><option>High</option></select>
    <button type="submit">Add task</button>
    <button type="button" class="secondary" (click)="tasks.set(makeTasksForTemplate(100))">Load 100</button>
    <button type="button" class="secondary" (click)="tasks.set([])">Clear</button>
  </form>

  @if (metrics(); as values) {
    <section class="panel">
      <div class="metrics">
        @for (entry of metricEntries(values); track entry[0]) {
          <div class="metric"><span>{{ entry[0] }}</span><strong>{{ entry[1].ms.toFixed(2) }} ms</strong><small>{{ entry[1].heapMB ?? 'n/a' }} MB heap</small></div>
        }
      </div>
      <div class="toolbar"><button (click)="downloadResults()">Download JSON</button></div>
    </section>
  }

  <section class="panel">
    <strong>{{ tasks().length }} tasks</strong>
    <div class="table-wrap"><table>
      <thead><tr><th>Task</th><th>Priority</th><th>Actions</th></tr></thead>
      <tbody>
        @for (task of tasks(); track task.id) {
          <tr>
            <td>{{ task.name }}</td><td class="priority">{{ task.priority }}</td>
            <td><div class="task-actions"><button (click)="updateTask(task.id)">Edit</button><button (click)="removeTask(task.id)">Remove</button></div></td>
          </tr>
        }
      </tbody>
    </table></div>
  </section>
</main>

// dom-framework-benchmark/svelte/src/App.svelte
<script>
  import { tick } from 'svelte';
  import {
    makeTasks, mutateFirst50, deleteFirst50,
    afterPaint, heapMB, median, downloadResults
  } from './benchmark-utils.js';

  let tasks = $state([]);
  let name = $state('');
  let priority = $state('Medium');
  let metrics = $state(null);
  let running = $state(false);

  function addTask(event) {
    event.preventDefault();
    if (!name.trim()) return;
    tasks = [...tasks, { id: Date.now(), name: name.trim(), priority }];
    name = '';
  }
  function updateTask(id) {
    tasks = tasks.map(t => t.id === id ? { ...t, name: `${t.name} edited` } : t);
  }
  function removeTask(id) {
    tasks = tasks.filter(t => t.id !== id);
  }
  async function sample(operation) {
    const start = performance.now();
    operation();
    await tick();
    await afterPaint();
    return performance.now() - start;
  }
  async function runBenchmark() {
    running = true;
    const results = {};

    for (const count of [100, 500, 1000]) {
      const samples = [];
      for (let i = 0; i < 5; i++) {
        tasks = []; await tick(); await afterPaint();
        samples.push(await sample(() => { tasks = makeTasks(count); }));
      }
      results[`render_${count}`] = { ms: median(samples), heapMB: heapMB() };
    }

    const updateSamples = [];
    for (let i = 0; i < 5; i++) {
      tasks = makeTasks(1000); await tick(); await afterPaint();
      updateSamples.push(await sample(() => { tasks = mutateFirst50(tasks); }));
    }
    results.update_50 = { ms: median(updateSamples), heapMB: heapMB() };

    const deleteSamples = [];
    for (let i = 0; i < 5; i++) {
      tasks = makeTasks(1000); await tick(); await afterPaint();
      deleteSamples.push(await sample(() => { tasks = deleteFirst50(tasks); }));
    }
    results.delete_50 = { ms: median(deleteSamples), heapMB: heapMB() };

    metrics = results;
    running = false;
  }
</script>

<main class="app">
  <header>
    <div><div class="eyebrow">Svelte DOM Benchmark</div><h1>TodoBench</h1><div class="muted">Compiled reactivity + keyed each blocks</div></div>
    <button onclick={runBenchmark} disabled={running}>{running ? 'Benchmarking…' : 'Run benchmark'}</button>
  </header>

  <form class="form-row" onsubmit={addTask}>
    <input bind:value={name} placeholder="Task name">
    <select bind:value={priority}><option>Low</option><option>Medium</option><option>High</option></select>
    <button type="submit">Add task</button>
    <button type="button" class="secondary" onclick={() => tasks = makeTasks(100)}>Load 100</button>
    <button type="button" class="secondary" onclick={() => tasks = []}>Clear</button>
  </form>

  {#if metrics}
    <section class="panel">
      <div class="metrics">
        {#each Object.entries(metrics) as [key, value] (key)}
          <div class="metric"><span>{key}</span><strong>{value.ms.toFixed(2)} ms</strong><small>{value.heapMB ?? 'n/a'} MB heap</small></div>
        {/each}
      </div>
      <div class="toolbar"><button onclick={() => downloadResults('Svelte', metrics)}>Download JSON</button></div>
    </section>
  {/if}

  <section class="panel">
    <strong>{tasks.length} tasks</strong>
    <div class="table-wrap"><table>
      <thead><tr><th>Task</th><th>Priority</th><th>Actions</th></tr></thead>
      <tbody>
        {#each tasks as task (task.id)}
          <tr>
            <td>{task.name}</td><td class="priority">{task.priority}</td>
            <td><div class="task-actions"><button onclick={() => updateTask(task.id)}>Edit</button><button onclick={() => removeTask(task.id)}>Remove</button></div></td>
          </tr>
        {/each}
      </tbody>
    </table></div>
  </section>
</main>
